# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/suggestions/suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/suggestions/suggestions.proto\x12\x0bsuggestions\"%\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\"+\n\x16\x42ookSuggestionsRequest\x12\x11\n\tnum_books\x18\x01 \x01(\x05\";\n\x17\x42ookSuggestionsResponse\x12 \n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x11.suggestions.Book2n\n\x0f\x42ookSuggestions\x12[\n\x0eGetSuggestions\x12#.suggestions.BookSuggestionsRequest\x1a$.suggestions.BookSuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.suggestions.suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOK']._serialized_start=55
  _globals['_BOOK']._serialized_end=92
  _globals['_BOOKSUGGESTIONSREQUEST']._serialized_start=94
  _globals['_BOOKSUGGESTIONSREQUEST']._serialized_end=137
  _globals['_BOOKSUGGESTIONSRESPONSE']._serialized_start=139
  _globals['_BOOKSUGGESTIONSRESPONSE']._serialized_end=198
  _globals['_BOOKSUGGESTIONS']._serialized_start=200
  _globals['_BOOKSUGGESTIONS']._serialized_end=310
# @@protoc_insertion_point(module_scope)
