version: "3.8"
services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - "5001:5000"

  fraud_detection:
    build:
      context: .
      dockerfile: fraud_detection/Dockerfile
    ports:
      - "50051:50051"

  transaction_verification:
    build:
      context: .
      dockerfile: transaction_verification/Dockerfile
    ports:
      - "50052:50052"

  suggestions:
    build:
      context: .
      dockerfile: suggestions/Dockerfile
    ports:
      - "50053:50053"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

