version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html

  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./orchestrator/src:/app/orchestrator/src
      - ./utils:/app/utils


  fraud_detection:
    build:
      context: ./
      dockerfile: ./fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/fraud_detection/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./fraud_detection/src:/app/fraud_detection/src

  transaction_verification:
    build:
      context: ./
      dockerfile: ./transaction_verification/Dockerfile
    ports:
      - 50052:50052
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/transaction_verification/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./transaction_verification/src:/app/transaction_verification/src

  suggestions:
    build:
      context: ./
      dockerfile: ./suggestions/Dockerfile
    ports:
      - 50053:50053
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/suggestions/src/app.py
      #OpenAI API key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./utils:/app/utils
      - ./suggestions/src:/app/suggestions/src


  order_queue:
    build:
      # Use the current directory as the build context
      # This allows us to access the files in the current directory inside the Dockerfile
      context: ./
      # Use the Dockerfile in the fraud_detection directorys
      dockerfile: ./order_queue/Dockerfile
    ports:
      # Expose port 50051 on the host, and map port 50051 of the container to port 50051 on the host
      - 50054:50054
    environment:
      # Pass the environment variables to the container
      # The PYTHONUNBUFFERED environment variable ensures that the output from the application is logged to the console
      - PYTHONUNBUFFERED=TRUE
      # The PYTHONFILE environment variable specifies the absolute entry point of the application
      # Check app.py in the suggestions directory to see how this is used
      - PYTHONFILE=/app/order_queue/src/app.py
    volumes:
      # Mount the utils directory in the current directory to the /app/utils directory in the container
      - ./utils:/app/utils
      # Mount the suggestions/src directory in the current directory to the /app/suggestions/src directory in the container
      - ./order_queue/src:/app/order_queue/src


  order_executor1:
      # The name of this service is "order_executor1"
      build:
        context: ./
        dockerfile: ./order_executor/Dockerfile
      # Our code references "order_executor{pid}:50056" – so for ID=1 => "order_executor1:50056"
      # We pass arguments to 'app.py':
      command: ["python", "/app/order_executor/src/app.py", "--instance_id", "1", "--executor_ids", "1,2,3"]
      environment:
        - PYTHONUNBUFFERED=TRUE
        - ORDER_QUEUE_ADDR=order_queue:50054
      # We only need 'expose' for internal communication;
      # or we can do ports: ["50056:50056"] if we want access from host.
      expose:
        - "50056"
      volumes:
        - ./utils:/app/utils
        - ./order_executor/src:/app/order_executor/src
      depends_on:
        - order_queue

  order_executor2:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    command: ["python", "/app/order_executor/src/app.py", "--instance_id", "2", "--executor_ids", "1,2,3"]
    environment:
      - PYTHONUNBUFFERED=TRUE
      - ORDER_QUEUE_ADDR=order_queue:50054
    expose:
      - "50056"
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
    depends_on:
      - order_queue

  order_executor3:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    command: ["python", "/app/order_executor/src/app.py", "--instance_id", "3", "--executor_ids", "1,2,3"]
    environment:
      - PYTHONUNBUFFERED=TRUE
      - ORDER_QUEUE_ADDR=order_queue:50054
    expose:
      - "50056"
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
    depends_on:
      - order_queue


  books_primary:
    build:
      context: ./books_database
      dockerfile: ./Dockerfile
    command:
      - python
      - "/app/books_database/src/app.py"
      - primary
      - books_backup1:50056
      - books_backup2:50056
    ports:
      - "50055:50055"       # primary listens internally on 50055
    expose:
      - "50055"
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src

  books_backup1:
    build:
      context: ./books_database
      dockerfile: ./Dockerfile
    command:
      - python
      - "/app/books_database/src/app.py"
      - backup
      - "50056"
    expose:
      - "50056"
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src

  books_backup2:
    build:
      context: ./books_database
      dockerfile: ./Dockerfile
    command:
      - python
      - "/app/books_database/src/app.py"
      - backup
      - "50056"
    expose:
      - "50056"
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src
  
  
  payment:
    build:
      context: ./payment
      dockerfile: ./Dockerfile
    ports:
      - "50065:50055"     
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/payment/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./payment/src:/app/payment/src