# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tmyservice\"\x19\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\"m\n\x0bVectorClock\x12\x30\n\x05\x63lock\x18\x01 \x03(\x0b\x32!.myservice.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"3\n\x10HoldOrderRequest\x12\x1f\n\x05order\x18\x01 \x01(\x0b\x32\x10.myservice.Order\"H\n\x11HoldOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\"\n\x02vc\x18\x02 \x01(\x0b\x32\x16.myservice.VectorClock\"4\n\x0c\x45ventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\"[\n\rEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\"\n\x02vc\x18\x02 \x01(\x0b\x32\x16.myservice.VectorClock\x12\x15\n\rerror_message\x18\x03 \x01(\t\"O\n\x11\x43learOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12(\n\x08\x66inal_vc\x18\x02 \x01(\x0b\x32\x16.myservice.VectorClock\"<\n\x12\x43learOrderResponse\x12\x0f\n\x07\x63leared\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xdd\x01\n\tMyService\x12\x46\n\tHoldOrder\x12\x1b.myservice.HoldOrderRequest\x1a\x1c.myservice.HoldOrderResponse\x12=\n\x08RunEvent\x12\x17.myservice.EventRequest\x1a\x18.myservice.EventResponse\x12I\n\nClearOrder\x12\x1c.myservice.ClearOrderRequest\x1a\x1d.myservice.ClearOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_ORDER']._serialized_start=28
  _globals['_ORDER']._serialized_end=53
  _globals['_VECTORCLOCK']._serialized_start=55
  _globals['_VECTORCLOCK']._serialized_end=164
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=120
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=164
  _globals['_HOLDORDERREQUEST']._serialized_start=166
  _globals['_HOLDORDERREQUEST']._serialized_end=217
  _globals['_HOLDORDERRESPONSE']._serialized_start=219
  _globals['_HOLDORDERRESPONSE']._serialized_end=291
  _globals['_EVENTREQUEST']._serialized_start=293
  _globals['_EVENTREQUEST']._serialized_end=345
  _globals['_EVENTRESPONSE']._serialized_start=347
  _globals['_EVENTRESPONSE']._serialized_end=438
  _globals['_CLEARORDERREQUEST']._serialized_start=440
  _globals['_CLEARORDERREQUEST']._serialized_end=519
  _globals['_CLEARORDERRESPONSE']._serialized_start=521
  _globals['_CLEARORDERRESPONSE']._serialized_end=581
  _globals['_MYSERVICE']._serialized_start=584
  _globals['_MYSERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
