# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class MyServiceStub(object):
    """Service definition with the new RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HoldOrder = channel.unary_unary(
                '/myservice.MyService/HoldOrder',
                request_serializer=service__pb2.HoldOrderRequest.SerializeToString,
                response_deserializer=service__pb2.HoldOrderResponse.FromString,
                )
        self.RunEvent = channel.unary_unary(
                '/myservice.MyService/RunEvent',
                request_serializer=service__pb2.EventRequest.SerializeToString,
                response_deserializer=service__pb2.EventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/myservice.MyService/ClearOrder',
                request_serializer=service__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=service__pb2.ClearOrderResponse.FromString,
                )


class MyServiceServicer(object):
    """Service definition with the new RPCs.
    """

    def HoldOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HoldOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.HoldOrder,
                    request_deserializer=service__pb2.HoldOrderRequest.FromString,
                    response_serializer=service__pb2.HoldOrderResponse.SerializeToString,
            ),
            'RunEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunEvent,
                    request_deserializer=service__pb2.EventRequest.FromString,
                    response_serializer=service__pb2.EventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=service__pb2.ClearOrderRequest.FromString,
                    response_serializer=service__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservice.MyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyService(object):
    """Service definition with the new RPCs.
    """

    @staticmethod
    def HoldOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.MyService/HoldOrder',
            service__pb2.HoldOrderRequest.SerializeToString,
            service__pb2.HoldOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.MyService/RunEvent',
            service__pb2.EventRequest.SerializeToString,
            service__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.MyService/ClearOrder',
            service__pb2.ClearOrderRequest.SerializeToString,
            service__pb2.ClearOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
