# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/fraud_detection/fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.utils/pb/fraud_detection/fraud_detection.proto\x12\x0f\x66raud_detection\"O\n\x0bPaymentInfo\x12\x1a\n\x12\x63redit_card_number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"3\n\x0cOrderDetails\x12\r\n\x05\x62ooks\x18\x01 \x03(\t\x12\x14\n\x0ctotal_amount\x18\x02 \x01(\x01\"\x98\x01\n\x11\x46raudCheckRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12-\n\x07payment\x18\x02 \x01(\x0b\x32\x1c.fraud_detection.PaymentInfo\x12,\n\x05order\x18\x03 \x01(\x0b\x32\x1d.fraud_detection.OrderDetails\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\"<\n\x12\x46raudCheckResponse\x12\x15\n\ris_fraudulent\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2g\n\x0e\x46raudDetection\x12U\n\nCheckFraud\x12\".fraud_detection.FraudCheckRequest\x1a#.fraud_detection.FraudCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.fraud_detection.fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYMENTINFO']._serialized_start=67
  _globals['_PAYMENTINFO']._serialized_end=146
  _globals['_ORDERDETAILS']._serialized_start=148
  _globals['_ORDERDETAILS']._serialized_end=199
  _globals['_FRAUDCHECKREQUEST']._serialized_start=202
  _globals['_FRAUDCHECKREQUEST']._serialized_end=354
  _globals['_FRAUDCHECKRESPONSE']._serialized_start=356
  _globals['_FRAUDCHECKRESPONSE']._serialized_end=416
  _globals['_FRAUDDETECTION']._serialized_start=418
  _globals['_FRAUDDETECTION']._serialized_end=521
# @@protoc_insertion_point(module_scope)
