# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x0border_queue\"K\n\x11OrderQueueRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x12\n\norder_data\x18\x03 \x01(\t\"6\n\x12OrderQueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x13OrderDequeueRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\"^\n\x14OrderDequeueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x12\n\norder_data\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t2\xa8\x01\n\nOrderQueue\x12J\n\x07\x45nqueue\x12\x1e.order_queue.OrderQueueRequest\x1a\x1f.order_queue.OrderQueueResponse\x12N\n\x07\x44\x65queue\x12 .order_queue.OrderDequeueRequest\x1a!.order_queue.OrderDequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERQUEUEREQUEST']._serialized_start=55
  _globals['_ORDERQUEUEREQUEST']._serialized_end=130
  _globals['_ORDERQUEUERESPONSE']._serialized_start=132
  _globals['_ORDERQUEUERESPONSE']._serialized_end=186
  _globals['_ORDERDEQUEUEREQUEST']._serialized_start=188
  _globals['_ORDERDEQUEUEREQUEST']._serialized_end=230
  _globals['_ORDERDEQUEUERESPONSE']._serialized_start=232
  _globals['_ORDERDEQUEUERESPONSE']._serialized_end=326
  _globals['_ORDERQUEUE']._serialized_start=329
  _globals['_ORDERQUEUE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
