# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_queue_pb2 as utils_dot_pb_dot_order__queue_dot_order__queue__pb2


class OrderQueueStub(object):
    """The OrderQueue service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/order_queue.OrderQueue/Enqueue',
                request_serializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderQueueRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderQueueResponse.FromString,
                )
        self.Dequeue = channel.unary_unary(
                '/order_queue.OrderQueue/Dequeue',
                request_serializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderDequeueRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderDequeueResponse.FromString,
                )


class OrderQueueServicer(object):
    """The OrderQueue service definition
    """

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderQueueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderQueueRequest.FromString,
                    response_serializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderQueueResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderDequeueRequest.FromString,
                    response_serializer=utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderDequeueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_queue.OrderQueue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderQueue(object):
    """The OrderQueue service definition
    """

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_queue.OrderQueue/Enqueue',
            utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderQueueRequest.SerializeToString,
            utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_queue.OrderQueue/Dequeue',
            utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderDequeueRequest.SerializeToString,
            utils_dot_pb_dot_order__queue_dot_order__queue__pb2.OrderDequeueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
