# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\norderqueue\x1a\x1bgoogle/protobuf/empty.proto\"K\n\x11OrderQueueRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x12\n\norder_data\x18\x03 \x01(\t\"6\n\x12OrderQueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\x0fOrderQueueOrder\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x12\n\norder_data\x18\x03 \x01(\t2\x96\x01\n\nOrderQueue\x12H\n\x07\x45nqueue\x12\x1d.orderqueue.OrderQueueRequest\x1a\x1e.orderqueue.OrderQueueResponse\x12>\n\x07\x44\x65queue\x12\x16.google.protobuf.Empty\x1a\x1b.orderqueue.OrderQueueOrderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERQUEUEREQUEST']._serialized_start=83
  _globals['_ORDERQUEUEREQUEST']._serialized_end=158
  _globals['_ORDERQUEUERESPONSE']._serialized_start=160
  _globals['_ORDERQUEUERESPONSE']._serialized_end=214
  _globals['_ORDERQUEUEORDER']._serialized_start=216
  _globals['_ORDERQUEUEORDER']._serialized_end=289
  _globals['_ORDERQUEUE']._serialized_start=292
  _globals['_ORDERQUEUE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
