# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dorder_queue/order_queue.proto\x12\x0border_queue\"-\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_data\x18\x02 \x01(\t\"1\n\rQueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2z\n\nOrderQueue\x12\x39\n\x07\x45nqueue\x12\x12.order_queue.Order\x1a\x1a.order_queue.QueueResponse\x12\x31\n\x07\x44\x65queue\x12\x12.order_queue.Empty\x1a\x12.order_queue.Orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=46
  _globals['_ORDER']._serialized_end=91
  _globals['_QUEUERESPONSE']._serialized_start=93
  _globals['_QUEUERESPONSE']._serialized_end=142
  _globals['_EMPTY']._serialized_start=144
  _globals['_EMPTY']._serialized_end=151
  _globals['_ORDERQUEUE']._serialized_start=153
  _globals['_ORDERQUEUE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
