# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transaction_verification_pb2 as utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2


class TransactionVerificationStub(object):
    """The service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateTransaction = channel.unary_unary(
                '/transaction_verification.TransactionVerification/ValidateTransaction',
                request_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationResponse.FromString,
                )
        self.InitOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerification/InitOrder',
                request_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderInitRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderInitResponse.FromString,
                )
        self.VerifyItems = channel.unary_unary(
                '/transaction_verification.TransactionVerification/VerifyItems',
                request_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
                )
        self.VerifyUserData = channel.unary_unary(
                '/transaction_verification.TransactionVerification/VerifyUserData',
                request_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
                )
        self.VerifyCreditCard = channel.unary_unary(
                '/transaction_verification.TransactionVerification/VerifyCreditCard',
                request_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerification/ClearOrder',
                request_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.ClearOrderResponse.FromString,
                )


class TransactionVerificationServicer(object):
    """The service definition
    """

    def ValidateTransaction(self, request, context):
        """Old single-call approach (optional):
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitOrder(self, request, context):
        """Init / store data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyItems(self, request, context):
        """New event-based calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Final cleanup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTransaction,
                    request_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationRequest.FromString,
                    response_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationResponse.SerializeToString,
            ),
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderInitRequest.FromString,
                    response_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderInitResponse.SerializeToString,
            ),
            'VerifyItems': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyItems,
                    request_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.FromString,
                    response_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.SerializeToString,
            ),
            'VerifyUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUserData,
                    request_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.FromString,
                    response_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.SerializeToString,
            ),
            'VerifyCreditCard': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCreditCard,
                    request_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.FromString,
                    response_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.ClearOrderRequest.FromString,
                    response_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionVerification(object):
    """The service definition
    """

    @staticmethod
    def ValidateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerification/ValidateTransaction',
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationRequest.SerializeToString,
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerification/InitOrder',
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderInitRequest.SerializeToString,
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerification/VerifyItems',
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerification/VerifyUserData',
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyCreditCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerification/VerifyCreditCard',
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerification/ClearOrder',
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.ClearOrderRequest.SerializeToString,
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.ClearOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
