# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transaction_verification_pb2 as utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2


class TransactionVerificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateTransaction = channel.unary_unary(
                '/transaction_verification.TransactionVerification/ValidateTransaction',
                request_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationResponse.FromString,
                )


class TransactionVerificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTransaction,
                    request_deserializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationRequest.FromString,
                    response_serializer=utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionVerification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerification/ValidateTransaction',
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationRequest.SerializeToString,
            utils_dot_pb_dot_transaction__verification_dot_transaction__verification__pb2.TransactionValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
