# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2]\n\rOrderExecutor\x12L\n\x0bHealthCheck\x12\x1d.order_executor.HealthRequest\x1a\x1e.order_executor.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHREQUEST']._serialized_start=40
  _globals['_HEALTHREQUEST']._serialized_end=55
  _globals['_HEALTHRESPONSE']._serialized_start=57
  _globals['_HEALTHRESPONSE']._serialized_end=89
  _globals['_ORDEREXECUTOR']._serialized_start=91
  _globals['_ORDEREXECUTOR']._serialized_end=184
# @@protoc_insertion_point(module_scope)
