# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_executor/order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/order_executor/order_executor.proto\x12\x0eorder_executor\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\x0f\x45lectionRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\"\x1e\n\x10\x45lectionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\",\n\x12\x43oordinatorRequest\x12\x16\n\x0e\x63oordinator_id\x18\x01 \x01(\x05\"\x12\n\x10HeartbeatRequest\"9\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x15\n\rleader_status\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc9\x02\n\rOrderExecutor\x12M\n\x08\x45lection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12I\n\x0b\x43oordinator\x12\".order_executor.CoordinatorRequest\x1a\x16.google.protobuf.Empty\x12P\n\tHeartbeat\x12 .order_executor.HeartbeatRequest\x1a!.order_executor.HeartbeatResponse\x12L\n\x0bHealthCheck\x12\x1d.order_executor.HealthRequest\x1a\x1e.order_executor.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_executor.order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ELECTIONREQUEST']._serialized_start=93
  _globals['_ELECTIONREQUEST']._serialized_end=132
  _globals['_ELECTIONRESPONSE']._serialized_start=134
  _globals['_ELECTIONRESPONSE']._serialized_end=164
  _globals['_COORDINATORREQUEST']._serialized_start=166
  _globals['_COORDINATORREQUEST']._serialized_end=210
  _globals['_HEARTBEATREQUEST']._serialized_start=212
  _globals['_HEARTBEATREQUEST']._serialized_end=230
  _globals['_HEARTBEATRESPONSE']._serialized_start=232
  _globals['_HEARTBEATRESPONSE']._serialized_end=289
  _globals['_HEALTHREQUEST']._serialized_start=291
  _globals['_HEALTHREQUEST']._serialized_end=306
  _globals['_HEALTHRESPONSE']._serialized_start=308
  _globals['_HEALTHRESPONSE']._serialized_end=340
  _globals['_ORDEREXECUTOR']._serialized_start=343
  _globals['_ORDEREXECUTOR']._serialized_end=672
# @@protoc_insertion_point(module_scope)
