# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"(\n\x12TransactionRequest\x12\x12\n\norder_json\x18\x01 \x01(\t\"\'\n\x13TransactionResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\x8b\x01\n\x17TransactionVerification\x12p\n\x11VerifyTransaction\x12,.transaction_verification.TransactionRequest\x1a-.transaction_verification.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=60
  _globals['_TRANSACTIONREQUEST']._serialized_end=100
  _globals['_TRANSACTIONRESPONSE']._serialized_start=102
  _globals['_TRANSACTIONRESPONSE']._serialized_end=141
  _globals['_TRANSACTIONVERIFICATION']._serialized_start=144
  _globals['_TRANSACTIONVERIFICATION']._serialized_end=283
# @@protoc_insertion_point(module_scope)
