# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/payment/payment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eutils/pb/payment/payment.proto\x12\x07payment\x1a\x1bgoogle/protobuf/empty.proto\"\\\n\x15PreparePaymentRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cuser_contact\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\"\'\n\x16PreparePaymentResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"3\n\x16\x46inalizePaymentRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x61\x62ort\x18\x02 \x01(\x08\x32\xaf\x01\n\x0ePaymentService\x12Q\n\x0ePreparePayment\x12\x1e.payment.PreparePaymentRequest\x1a\x1f.payment.PreparePaymentResponse\x12J\n\x0f\x46inalizePayment\x12\x1f.payment.FinalizePaymentRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.payment.payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREPAREPAYMENTREQUEST']._serialized_start=72
  _globals['_PREPAREPAYMENTREQUEST']._serialized_end=164
  _globals['_PREPAREPAYMENTRESPONSE']._serialized_start=166
  _globals['_PREPAREPAYMENTRESPONSE']._serialized_end=205
  _globals['_FINALIZEPAYMENTREQUEST']._serialized_start=207
  _globals['_FINALIZEPAYMENTREQUEST']._serialized_end=258
  _globals['_PAYMENTSERVICE']._serialized_start=261
  _globals['_PAYMENTSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
